
import React, { useState } from 'react';
import { ViewState } from '../types';
import * as Icons from 'lucide-react';

interface LegalPageProps {
  onNavigate: (view: ViewState) => void;
}

type Tab = 'terms' | 'privacy' | 'refund';

export const LegalPage: React.FC<LegalPageProps> = ({ onNavigate }) => {
  const [activeTab, setActiveTab] = useState<Tab>('terms');

  return (
    <div className="max-w-5xl mx-auto animate-fade-in pb-10">
      <div className="mb-6">
        <button 
            onClick={() => onNavigate('profile')} 
            className="flex items-center gap-2 text-slate-500 hover:text-slate-800 transition-colors text-sm font-medium mb-6"
        >
            <Icons.ArrowLeft className="w-4 h-4" /> Back to Profile
        </button>
        <h1 className="text-2xl md:text-3xl font-heading font-bold text-slate-900">Legal & Privacy</h1>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          
          {/* Sidebar Tabs */}
          <div className="md:col-span-1 space-y-2">
             <button 
                onClick={() => setActiveTab('terms')}
                className={`w-full text-left px-4 py-3 rounded-xl text-sm font-bold transition-colors ${activeTab === 'terms' ? 'bg-slate-900 text-white shadow-md' : 'bg-white text-slate-600 hover:bg-slate-50'}`}
             >
                Terms & Conditions
             </button>
             <button 
                onClick={() => setActiveTab('privacy')}
                className={`w-full text-left px-4 py-3 rounded-xl text-sm font-bold transition-colors ${activeTab === 'privacy' ? 'bg-slate-900 text-white shadow-md' : 'bg-white text-slate-600 hover:bg-slate-50'}`}
             >
                Privacy Policy
             </button>
             <button 
                onClick={() => setActiveTab('refund')}
                className={`w-full text-left px-4 py-3 rounded-xl text-sm font-bold transition-colors ${activeTab === 'refund' ? 'bg-slate-900 text-white shadow-md' : 'bg-white text-slate-600 hover:bg-slate-50'}`}
             >
                Refund & Cancellation
             </button>
          </div>

          {/* Content Area */}
          <div className="md:col-span-3 bg-white rounded-2xl border border-slate-200 shadow-sm p-8 text-slate-700 leading-relaxed text-sm h-[600px] overflow-y-auto">
             
             {activeTab === 'terms' && (
                <div className="space-y-6">
                   <h2 className="text-xl font-bold text-slate-900 pb-2 border-b border-slate-100">Terms and Conditions</h2>
                   <p className="text-xs text-slate-400">Last updated: Oct 24, 2023</p>
                   
                   <section>
                      <h3 className="font-bold text-slate-900 mb-2">1. Introduction</h3>
                      <p>Welcome to Unlockify.in. By accessing or using our website and services, you agree to be bound by these Terms and Conditions. If you disagree with any part of these terms, you may not use our services.</p>
                   </section>
                   <section>
                      <h3 className="font-bold text-slate-900 mb-2">2. Accounts</h3>
                      <p>When you create an account with us, you must provide us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account.</p>
                   </section>
                   <section>
                      <h3 className="font-bold text-slate-900 mb-2">3. Intellectual Property</h3>
                      <p>The Service and its original content, features, and functionality are and will remain the exclusive property of Unlockify Solutions Pvt Ltd and its licensors. Content generated by AI for you is yours to use for your business marketing.</p>
                   </section>
                   <section>
                      <h3 className="font-bold text-slate-900 mb-2">4. Limitations</h3>
                      <p>In no event shall Unlockify.in, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages.</p>
                   </section>
                </div>
             )}

             {activeTab === 'privacy' && (
                <div className="space-y-6">
                   <h2 className="text-xl font-bold text-slate-900 pb-2 border-b border-slate-100">Privacy Policy</h2>
                   <p className="text-xs text-slate-400">Last updated: Oct 24, 2023</p>
                   
                   <section>
                      <h3 className="font-bold text-slate-900 mb-2">1. Data Collection</h3>
                      <p>We collect information that you provide directly to us, such as when you create an account, update your profile, or communicate with us. This includes name, email, phone number, and business details.</p>
                   </section>
                   <section>
                      <h3 className="font-bold text-slate-900 mb-2">2. Use of Data</h3>
                      <p>We use the data to provide, maintain, and improve our services, including to generate personalized marketing content. We do not sell your personal data to third parties.</p>
                   </section>
                   <section>
                      <h3 className="font-bold text-slate-900 mb-2">3. Data Security</h3>
                      <p>We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet is 100% secure.</p>
                   </section>
                </div>
             )}

             {activeTab === 'refund' && (
                <div className="space-y-6">
                   <h2 className="text-xl font-bold text-slate-900 pb-2 border-b border-slate-100">Refund & Cancellation Policy</h2>
                   <p className="text-xs text-slate-400">Last updated: Oct 24, 2023</p>
                   
                   <section>
                      <h3 className="font-bold text-slate-900 mb-2">1. Cancellation</h3>
                      <p>You may cancel your subscription at any time. Cancellation will take effect at the end of the current billing period. You will continue to have access to the service until the end of your billing period.</p>
                   </section>
                   <section>
                      <h3 className="font-bold text-slate-900 mb-2">2. Refunds</h3>
                      <p>We offer a 7-day money-back guarantee for new subscribers. If you are not satisfied with our service within the first 7 days of your first subscription payment, please contact support for a full refund. Refunds for subsequent months are generally not provided unless there is a system error or outage.</p>
                   </section>
                   <section>
                      <h3 className="font-bold text-slate-900 mb-2">3. Processing</h3>
                      <p>Refunds are processed within 5-7 business days to the original payment method.</p>
                   </section>
                </div>
             )}

          </div>
      </div>
    </div>
  );
};
